use anyhow::Result;
use chrono::Utc;
use tracing::info;

use crate::db::{Client, Gateway};
use crate::nftables::build_ruleset;

const SCRIPTS_DIR: &str = "/home/stellwerk";

/// Generate and write all persistence scripts
pub async fn write_all(
    clients: &[Client],
    gateways: &[Gateway],
    default_gw: &str,
) -> Result<()> {
    tokio::fs::create_dir_all(SCRIPTS_DIR).await?;

    write_failsafe_script().await?;
    write_apply_routing_script(clients, gateways, default_gw).await?;
    write_nftables_script(clients, gateways, default_gw).await?;

    info!("Persistence scripts written to {}", SCRIPTS_DIR);
    Ok(())
}

/// Minimal failsafe: ensures SSH access and default GRE route after reboot
async fn write_failsafe_script() -> Result<()> {
    let path = format!("{}/failsafe.sh", SCRIPTS_DIR);
    let content = r#"#!/bin/bash
# Stellwerk Failsafe Script
# Ensures SSH access and basic connectivity after reboot.
# Run this independently if stellwerk fails to start.
# Generated by stellwerk – do NOT edit manually.

set -e

echo "[stellwerk failsafe] Applying basic routing rules..."

# Ensure default route via GRE fiber
ip route replace default via 172.16.10.1 dev gre_fiber src 5.230.119.175 table gre_175 2>/dev/null || true

# Ensure default route in main table via GRE
ip route replace default via 172.16.10.1 dev gre_fiber src 5.230.119.175 2>/dev/null || true

# Allow SSH on all LAN interfaces (fallback – main firewall handles this)
echo "[stellwerk failsafe] Done."
"#;
    tokio::fs::write(&path, content).await?;
    // Make executable
    let _ = tokio::process::Command::new("chmod")
        .args(["+x", &path])
        .status()
        .await;
    Ok(())
}

/// Full routing script with all ip rule commands from current DB state
async fn write_apply_routing_script(
    clients: &[Client],
    gateways: &[Gateway],
    default_gw: &str,
) -> Result<()> {
    let path = format!("{}/apply-routing.sh", SCRIPTS_DIR);
    let ts = Utc::now().format("%Y-%m-%d %H:%M:%S UTC");
    let mut lines = Vec::new();

    lines.push("#!/bin/bash".to_string());
    lines.push(format!("# Stellwerk routing rules – generated {}", ts));
    lines.push("# Apply all client routing rules from last known state.".to_string());
    lines.push("# Run manually if stellwerk is not running.".to_string());
    lines.push(String::new());
    lines.push("# Remove old stellwerk rules (priority 1000-1999)".to_string());
    lines.push("ip rule show | awk -F: '{print $1}' | while read prio; do".to_string());
    lines.push("  if [ \"$prio\" -ge 1000 ] && [ \"$prio\" -lt 2000 ] 2>/dev/null; then".to_string());
    lines.push("    ip rule del priority $prio 2>/dev/null || true".to_string());
    lines.push("  fi".to_string());
    lines.push("done".to_string());
    lines.push(String::new());

    for client in clients {
        if client.active == 0 || client.gateway == default_gw {
            continue;
        }
        if let Some(gw) = gateways.iter().find(|g| g.name == client.gateway) {
            let priority = 1000 + gw.mark as u32;
            lines.push(format!(
                "ip rule add fwmark {} lookup {} priority {}  # {} ({})",
                gw.mark, gw.table_name, priority, client.ip,
                client.label.as_deref().unwrap_or(&client.gateway)
            ));
        }
    }

    lines.push(String::new());
    lines.push("echo 'Stellwerk routing rules applied.'".to_string());

    let content = lines.join("\n");
    tokio::fs::write(&path, content).await?;
    let _ = tokio::process::Command::new("chmod")
        .args(["+x", &path])
        .status()
        .await;
    Ok(())
}

/// Write the nftables rules as an includeable .nft file
async fn write_nftables_script(
    clients: &[Client],
    gateways: &[Gateway],
    default_gw: &str,
) -> Result<()> {
    let path = format!("{}/nftables-stellwerk.nft", SCRIPTS_DIR);
    let ts = Utc::now().format("%Y-%m-%d %H:%M:%S UTC");

    let ruleset = build_ruleset(clients, gateways, default_gw);
    let header = format!(
        "# Stellwerk nftables rules – generated {}\n# Apply with: nft -f {}\n\n",
        ts, path
    );

    tokio::fs::write(&path, format!("{}{}", header, ruleset)).await?;
    Ok(())
}
