use anyhow::Result;
use chrono::Utc;
use tracing::{info, warn};

use crate::config::DnsConfig;
use crate::db::{Client, Gateway};
use crate::nftables::build_ruleset;

const SCRIPTS_DIR: &str = "/home/stellwerk";

/// Generate and write all persistence scripts
pub async fn write_all(
    clients: &[Client],
    gateways: &[Gateway],
    default_gw: &str,
    dns: &DnsConfig,
) -> Result<()> {
    tokio::fs::create_dir_all(SCRIPTS_DIR).await?;

    write_failsafe_script().await?;
    write_apply_routing_script(clients, gateways, default_gw).await?;
    write_nftables_script(clients, gateways, default_gw, dns).await?;
    write_wg_helper_script().await?;

    info!("Persistence scripts written to {}", SCRIPTS_DIR);
    Ok(())
}

/// Minimal failsafe: ensures SSH access and default GRE route after reboot
async fn write_failsafe_script() -> Result<()> {
    let path = format!("{}/failsafe.sh", SCRIPTS_DIR);
    let content = r#"#!/bin/bash
# Stellwerk Failsafe Script
# Ensures SSH access and basic connectivity after reboot.
# Run this independently if stellwerk fails to start.
# Generated by stellwerk – do NOT edit manually.

set -e

echo "[stellwerk failsafe] Applying basic routing rules..."

# Ensure default route via GRE fiber
ip route replace default via 172.16.10.1 dev gre_fiber src 5.230.119.175 table gre_175 2>/dev/null || true

# Ensure default route in main table via GRE
ip route replace default via 172.16.10.1 dev gre_fiber src 5.230.119.175 2>/dev/null || true

# Allow SSH on all LAN interfaces (fallback – main firewall handles this)
echo "[stellwerk failsafe] Done."
"#;
    tokio::fs::write(&path, content).await?;
    // Make executable
    let _ = tokio::process::Command::new("chmod")
        .args(["+x", &path])
        .status()
        .await;
    Ok(())
}

/// Full routing script with all ip rule commands from current DB state
async fn write_apply_routing_script(
    clients: &[Client],
    gateways: &[Gateway],
    default_gw: &str,
) -> Result<()> {
    let path = format!("{}/apply-routing.sh", SCRIPTS_DIR);
    let ts = Utc::now().format("%Y-%m-%d %H:%M:%S UTC");
    let mut lines = Vec::new();

    lines.push("#!/bin/bash".to_string());
    lines.push(format!("# Stellwerk routing rules – generated {}", ts));
    lines.push("# Apply all client routing rules from last known state.".to_string());
    lines.push("# Run manually if stellwerk is not running.".to_string());
    lines.push(String::new());
    lines.push("# Remove old stellwerk rules (priority 1000-1999)".to_string());
    lines.push("ip rule show | awk -F: '{print $1}' | while read prio; do".to_string());
    lines.push("  if [ \"$prio\" -ge 1000 ] && [ \"$prio\" -lt 2000 ] 2>/dev/null; then".to_string());
    lines.push("    ip rule del priority $prio 2>/dev/null || true".to_string());
    lines.push("  fi".to_string());
    lines.push("done".to_string());
    lines.push(String::new());

    for client in clients {
        if client.active == 0 || client.gateway == default_gw {
            continue;
        }
        if let Some(gw) = gateways.iter().find(|g| g.name == client.gateway) {
            lines.push(format!(
                "ip rule add from {} lookup {} priority 1000  # {}",
                client.ip, gw.table_name,
                client.label.as_deref().unwrap_or(&client.gateway)
            ));
        }
    }

    // Fallback für alle LAN-Clients ohne spezifische Regel
    if let Some(gw) = gateways.iter().find(|g| g.name == default_gw) {
        lines.push(format!(
            "ip rule add from 172.16.0.0/12 lookup {} priority 1999  # Fallback default-gw",
            gw.table_name
        ));
    }

    lines.push(String::new());
    lines.push("echo 'Stellwerk routing rules applied.'".to_string());

    let content = lines.join("\n");
    tokio::fs::write(&path, content).await?;
    let _ = tokio::process::Command::new("chmod")
        .args(["+x", &path])
        .status()
        .await;
    Ok(())
}

/// WireGuard helper script (called via sudo for privileged wg-quick operations)
async fn write_wg_helper_script() -> Result<()> {
    let path = format!("{}/wg-helper.sh", SCRIPTS_DIR);
    let content = r#"#!/bin/bash
# Stellwerk WireGuard Helper
# Privilegierte WireGuard-Operationen für den stellwerk-User.
# Wird via sudo aufgerufen: sudo /home/stellwerk/wg-helper.sh {up|down|update} <cc>
# Sudoers: stellwerk ALL=(root) NOPASSWD: /home/stellwerk/wg-helper.sh
# Generated by stellwerk – do NOT edit manually.

set -e
ACTION="${1:-}"
CC="${2:-}"

if [ -z "$ACTION" ] || [ -z "$CC" ]; then
    echo "Usage: $0 {up|down|update} <country_code>" >&2
    exit 1
fi

STAGING="/home/stellwerk/wg/mu${CC}.conf"
ACTIVE="/etc/wireguard/mu${CC}.conf"
IFACE="mu${CC}"

case "$ACTION" in
  up)
    if [ ! -f "$STAGING" ]; then
        echo "Staging-Config nicht gefunden: $STAGING" >&2
        exit 1
    fi
    cp "$STAGING" "$ACTIVE"
    chmod 600 "$ACTIVE"
    wg-quick up "$ACTIVE"
    ;;
  down)
    wg-quick down "$ACTIVE" || true
    rm -f "$ACTIVE"
    ;;
  update)
    if [ ! -f "$STAGING" ]; then
        echo "Staging-Config nicht gefunden: $STAGING" >&2
        exit 1
    fi
    cp "$STAGING" "$ACTIVE"
    chmod 600 "$ACTIVE"
    wg syncconf "$IFACE" <(wg-quick strip "$ACTIVE")
    ;;
  *)
    echo "Unbekannte Aktion: $ACTION (erlaubt: up, down, update)" >&2
    exit 1
    ;;
esac
"#;
    tokio::fs::write(&path, content).await?;
    let _ = tokio::process::Command::new("chmod")
        .args(["+x", &path])
        .status()
        .await;
    Ok(())
}

/// Configure Unbound's outgoing interface for DNS-leak protection.
///
/// When the DNS gateway has a fixed src_ip (e.g. gre_175 → 5.230.119.175),
/// Unbound binds its outgoing socket to that IP directly. The existing
/// prio-1 rule `from 5.230.119.175 lookup gre_175` then routes DNS queries
/// through the correct gateway — no SNAT needed, no conntrack UDP issues.
///
/// For gateways without src_ip (e.g. ppp0), the config is cleared and the
/// fwmark-based routing in nftables/iproute2 handles it instead.
pub async fn configure_unbound(dns: &DnsConfig, gateways: &[Gateway]) -> Result<()> {
    const UNBOUND_STELLWERK_CONF: &str = "/etc/unbound/stellwerk.conf";

    let outgoing_ip = dns.gateway.as_deref().and_then(|gw_name| {
        gateways.iter()
            .find(|g| g.name == gw_name)
            .and_then(|g| g.src_ip.as_deref())
    });

    let content = match outgoing_ip {
        Some(ip) => format!("server:\n    outgoing-interface: {}\n", ip),
        None => String::new(),
    };

    tokio::fs::write(UNBOUND_STELLWERK_CONF, &content).await?;

    let status = tokio::process::Command::new("systemctl")
        .args(["restart", "unbound"])
        .status()
        .await?;

    if status.success() {
        match outgoing_ip {
            Some(ip) => info!("Unbound: outgoing-interface={} (via {})", ip, dns.gateway.as_deref().unwrap_or("")),
            None => info!("Unbound: outgoing-interface gelöscht, fwmark-Routing aktiv"),
        }
    } else {
        warn!("Unbound restart fehlgeschlagen");
    }

    Ok(())
}

/// Write the nftables rules as an includeable .nft file
async fn write_nftables_script(
    clients: &[Client],
    gateways: &[Gateway],
    default_gw: &str,
    dns: &DnsConfig,
) -> Result<()> {
    let path = format!("{}/nftables-stellwerk.nft", SCRIPTS_DIR);
    let ts = Utc::now().format("%Y-%m-%d %H:%M:%S UTC");

    let ruleset = build_ruleset(clients, gateways, &[], default_gw, dns);
    let header = format!(
        "# Stellwerk nftables rules – generated {}\n# Apply with: nft -f {}\n\n",
        ts, path
    );

    tokio::fs::write(&path, format!("{}{}", header, ruleset)).await?;
    Ok(())
}
